dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
install:
  - python setup.py install
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - conda env create -f environment-medaka.yml
  - conda activate fieldbioinformatics

script:
  # run the unit test
  - pytest
  # run the functional test for the nanopolish pipeline variant
  - ./test-runner.sh nanopolish
  # run the functional test for the medaka pipeline variant
  - conda deactivate && conda activate fieldbioinformatics-medaka
  - ./test-runner.sh medaka
