dist: xenial
language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f test-data/env-nanopolish.yml
  - conda env create -f test-data/env-medaka.yml
  - conda activate artic-nanopolish
  - python setup.py install

script:
  # run the unit tests
  - pytest -s artic/*_unit_test.py

  # run the pipeline test for the nanopolish pipeline variant (already in the correct env)
  - ./test-runner.sh nanopolish

  # activate the medaka env and install the pipeline into this env
  - conda deactivate && conda activate artic-medaka
  - python setup.py install

  # run the medaka-specific functional tests
  - pytest -s artic/*_medaka_test.py

  # run the pipeline test for the medaka pipeline variant
  - ./test-runner.sh medaka
