name: artic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic-porechop==0.3.2pre
  - bcftools=1.9
  - biopython=1.76
  - bwa=0.7.17
  - clint=0.5.1
  - longshot=0.4.1
  - medaka=0.12.1
  - minimap2=2.17
  - muscle=3.8
  - nanopolish=0.13.1
  - nomkl
  - pandas=0.23.0
  - pip
  - pysam=0.15.3
  - pytest
  - python=3.6
  - pyvcf=0.6.8
  - samtools=1.9
